name: 'Release'
on:
  push:
    branches:
      - test
      - main

jobs:
  release:
    name: 'Publish new version'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@1
    with:
      language: golang
      language-version: '1.19'
      prepare-command: |
        go build
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
