name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release project'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-sdk-changesets.yml@v1
    with:
      version-command: pnpm exec changeset version && bash ./sync-version.sh
      publish-command: pnpm exec changeset publish && go run generate.go
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
