name: Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  tests:
    name: Tests (GO ${{ matrix.go-version }})
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - name: Run tests
        run: cd test && go test